spring:
  application:
    name: web-server

server:
    port: 8080
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me


zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8082/resource/
    auth:
      path: /auth/**
      url: http://localhost:8081/auth/


