spring:
  application:
    name: resource

server:
    port: 8082
    context-path: /resource
    session:
      cookie:
       name: OAUTH2SESSION

security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/auth/oauth/check_token
    client:
      clientId: SampleClientId
      clientSecret: secret
      authorized-grant-types: authorization_code
      access-token-uri: http://localhost:8081/auth/oauth/token
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize