server:
  port: 8081
  context-path: /auth
spring:
  application:
    name: auth
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: SampleClientId
      client-secret: secret



